name: food-order-app

services:
  postgres:
    image: postgres:15
    container_name: food-order-app-postgres
    environment:
      POSTGRES_DB: food-order-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - food-order-app_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  food-order-app_postgres_data:
